# ใช้ Node.js เวอร์ชันล่าสุดเป็นเบส image
FROM node:latest

# สร้างไดเรกทอรีสำหรับแอพ
WORKDIR /usr/src/app

# คัดลอกไฟล์ package.json และ package-lock.json (ถ้ามี)
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกซอร์สโค้ดทั้งหมด
COPY . .

# เปิดพอร์ต 3000 สำหรับแอพ
EXPOSE 3000

# รันคำสั่งเพื่อเริ่มต้นแอพ
CMD ["node", "app.js"]